name: 'FHS - Release To Play Store'
description: 'Checkout Repository, Version Bump, Test & Analyze, Build Flutter App And Release It On Play Store'
inputs:
  keystore_base64:
    description: 'Base64 encoded keystore to sign the app'
    required: false
  key_properties:
    description: 'File with key properties. See https://docs.flutter.dev/deployment/android#reference-the-keystore-from-the-app'
    required: false
  service_account:
    description: 'Account key for GCP service account'
    required: false
  package_name:
    description: 'Package name'
    required: false
  create_release:
    descritpion: 'Add apk and aab as release to repository'
    required: false
    default: false
  qa:
    descritpion: 'Run flutter analyze and test'
    required: false
    default: true
  publish:
    description: 'Publish to stores'
    required: false
    default: true
  flutter_version:
    description: 'Flutter Version'
    required: false

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ inputs.flutter_version }}
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Flutter Test & Analyze
      shell: bash
      if: ${{ inputs.qa == 'true' }}
      run: |
        flutter test
        flutter analyze

    - name: Increase build number
      shell: bash
      run: |
        VERSION=$(grep -E "^version: " pubspec.yaml | cut -d" " -f2)
        V=$(echo $VERSION | cut -d+ -f1)
        BUILD=$(expr 1 + $(echo $VERSION | cut -d+ -f2))
        sed -i s/"^version:.*"/"version: $V+$BUILD"/g pubspec.yaml
    
    - name: Commit new build number
      uses: EndBug/add-and-commit@v9.1.4

    - name: Increase version number
      shell: bash
      run: |
        VERSION=$(grep -E "^version: " pubspec.yaml | cut -d" " -f2)
        V=$(expr 1 + $(echo $VERSION | cut -d+ -f1 | cut -d. -f1,2,3 | sed s/"\."//g))
        MAJOR=$(echo $V | cut -c1)
        MINOR=$(echo $V | cut -c2)
        PATCH=$(echo $V | cut -c3)
        BUILD=$(echo $VERSION | cut -d+ -f2)
        sed -i s/"^version:.*"/"version: $MAJOR.$MINOR.$PATCH+$BUILD"/g pubspec.yaml
        echo "APP_VERSION=$MAJOR.$MINOR.$PATCH+$BUILD" >> "$GITHUB_ENV"
    
    - name: Deserialize Secrets and replace storeFile entry
      shell: bash
      run: | 
        echo ${{ inputs.keystore_base64 }} | base64 -d > android/app/app.jks
        echo "${{ inputs.key_properties }}" | sed s/"storeFile=.*"/storeFile=app.jks/ > android/key.properties

    - name: Build Bundle and APK
      shell: bash
      run: | 
        flutter build appbundle
        flutter build apk

    - name: Create Release
      if: ${{ inputs.create_release == 'true' }}
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.APP_VERSION }}
        artifacts: "build/app/outputs/bundle/release/app-release.aab,build/app/outputs/flutter-apk/app-release.apk"

    - name: Prepare Package Name
      shell: bash
      if: ${{ inputs.publish == 'true' }}
      run: |
        PACKAGE_NAME=${{ inputs.package_name }}
        if [ -z $PACKAGE_NAME ]; then
          PACKAGE_NAME=$(grep applicationId android/app/build.gradle | tr "'" '"' | cut -d'"' -f2)
        fi
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> "$GITHUB_ENV"

    - name: Release To Play Store
      uses: r0adkll/upload-google-play@v1.1.3
      if: ${{ inputs.publish == 'true' }}
      with:
        serviceAccountJsonPlainText: ${{ inputs.service_account }}
        packageName:  ${{ env.PACKAGE_NAME }}
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: production
          
    - name: Commit new version number
      if: ${{ inputs.publish == 'true' }}
      uses: EndBug/add-and-commit@v9.1.4
    
    - name: Delete Secrets
      shell: bash
      run: |
        rm android/app/app.jks
        rm android/key.properties

