name: 'FHS - Release To Play Store'
description: 'Checkout Repository, Version Bump, Test & Analyze, Build Flutter App And Release It On Play Store'
inputs:
  keystore_base64:
    description: 'Base64 encoded keystore to sign the app'
    required: false
  key_properties_file:
    description: 'File with key properties. See https://docs.flutter.dev/deployment/android#reference-the-keystore-from-the-app'
    required: false
  service_account_base64:
    description: 'Base64 encoded key for GCP service account'
    required: false

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Print Content
      run: ls -la

