#!/bin/bash

if [ ! -e pubspec.yaml ]; then
    echo "[!] Call these scripts in the root directory of your flutter app"
    exit 1
fi

function pw {
    head -n 10 /dev/urandom | base64 | cut -c 1-64
}

case "$1" in
    signing)
        STORE_PASS=$(pw)
        KEY_PASS=$(pw)
        keytool -genkeypair -v -keystore $(basename $(pwd)).jks -storepass "$STORE_PASS" -keyalg RSA -keysize 2048 -validity 99999 -alias $(basename $(pwd))
        echo "storePassword=$STORE_PASS" >> key.properties
        echo "keyPassword=$KEY_PASS" >> key.properties
        echo "keyAlias=$(basename $(pwd))" >> key.properties
        echo "storeFile=app.jks" >> key.properties
        ;;
    *)
        echo -e "\nLaguna Studios presents Flutter Head Start"
        echo -e "------------------------------------------\n"
        echo "Available Commands:"
        echo "signing"
esac